export const MOTION_TOKENS = {
  durationShort: 0.16,
  durationMed: 0.22,
  durationAvatar: 0.22,
  durationSection: 0.42,
  durationTimelineDot: 0.8,
  durationTimelineLine: 1.5,
  durationTimelineDotReveal: 0.56,
  durationTimelineLineReveal: 0.75,
  durationTimelineLineDelay: 0.08,
  durationSkillEntry: 0.24,
  durationPortfolioEntry: 0.84,
  easingDefault: [0.22, 1, 0.36, 1] as const,
  easingReveal: [0.16, 1, 0.3, 1] as const,
  hoverElevate: -4,
  portfolioHoverScale: 1.055,
  portfolioHoverSpring: {
    type: "spring",
    stiffness: 260,
    damping: 24,
    mass: 0.7,
  } as const,
  pressScale: 0.97,
} as const;
